#!/usr/bin/env python3
"""
Tests for Session Fixation Protection (Security Issue #3)

This test suite verifies that the application properly prevents session fixation
attacks by regenerating the session ID after successful authentication.

OWASP Recommendation: "The session ID must be renewed or regenerated by the web 
application after any privilege level change within the associated user session."

Reference: https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html
"""

import os
import sys
import json
import base64
import pytest
from datetime import datetime, timedelta, timezone
from unittest.mock import Mock, patch, MagicMock

# Import the module under test
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from oauth import MemorySessionStore


class TestSessionFixationProtection:
    """Test suite for session fixation vulnerability fix (Issue #3)"""
    
    def test_session_regeneration_creates_new_id(self):
        """Test that regenerate_session creates a new session ID"""
        store = MemorySessionStore(ttl_seconds=3600)
        
        # Create initial session
        old_session_id, old_session_data = store.create_session()
        old_session_data['test_data'] = 'some_value'
        
        # Regenerate session
        new_session_id, new_session_data = store.regenerate_session(old_session_id)
        
        # Verify new session ID is different
        assert new_session_id is not None
        assert new_session_id != old_session_id
        assert len(new_session_id) > 0
    
    def test_session_regeneration_preserves_data(self):
        """Test that session data is preserved during regeneration"""
        store = MemorySessionStore(ttl_seconds=3600)
        
        # Create session with data
        old_session_id, old_session_data = store.create_session()
        old_session_data['user'] = {'sub': 'user123', 'email': 'test@example.com'}
        old_session_data['authenticated'] = True
        old_session_data['custom_field'] = 'custom_value'
        
        # Regenerate session
        new_session_id, new_session_data = store.regenerate_session(old_session_id)
        
        # Verify data is preserved
        assert new_session_data['user'] == {'sub': 'user123', 'email': 'test@example.com'}
        assert new_session_data['authenticated'] is True
        assert new_session_data['custom_field'] == 'custom_value'
    
    def test_session_regeneration_invalidates_old_session(self):
        """Test that old session ID is invalidated after regeneration"""
        store = MemorySessionStore(ttl_seconds=3600)
        
        # Create initial session
        old_session_id, old_session_data = store.create_session()
        old_session_data['authenticated'] = True
        
        # Regenerate session
        new_session_id, new_session_data = store.regenerate_session(old_session_id)
        
        # Try to access old session - should be None
        old_session_retrieved = store.get(old_session_id)
        assert old_session_retrieved is None
        
        # New session should be accessible
        new_session_retrieved = store.get(new_session_id)
        assert new_session_retrieved is not None
        assert new_session_retrieved['authenticated'] is True
    
    def test_session_regeneration_with_nonexistent_session(self):
        """Test regenerating a non-existent session returns None"""
        store = MemorySessionStore(ttl_seconds=3600)
        
        # Try to regenerate non-existent session
        new_session_id, new_session_data = store.regenerate_session('nonexistent_session_id')
        
        assert new_session_id is None
        assert new_session_data is None
    
    def test_session_regeneration_with_none_session_id(self):
        """Test regenerating with None session ID returns None"""
        store = MemorySessionStore(ttl_seconds=3600)
        
        # Try to regenerate with None
        new_session_id, new_session_data = store.regenerate_session(None)
        
        assert new_session_id is None
        assert new_session_data is None
    
    def test_session_regeneration_with_empty_session_id(self):
        """Test regenerating with empty session ID returns None"""
        store = MemorySessionStore(ttl_seconds=3600)
        
        # Try to regenerate with empty string
        new_session_id, new_session_data = store.regenerate_session('')
        
        assert new_session_id is None
        assert new_session_data is None
    
    def test_session_regeneration_updates_expiry(self):
        """Test that session expiry is updated during regeneration"""
        store = MemorySessionStore(ttl_seconds=3600)
        
        # Create session
        old_session_id, old_session_data = store.create_session()
        old_expiry = old_session_data['_session_expires_at']
        
        # Wait a moment to ensure time difference
        import time
        time.sleep(0.1)
        
        # Regenerate session
        new_session_id, new_session_data = store.regenerate_session(old_session_id)
        new_expiry = new_session_data['_session_expires_at']
        
        # New expiry should be later than old expiry
        assert new_expiry > old_expiry
    
    def test_session_regeneration_preserves_encrypted_tokens(self):
        """Test that encrypted tokens are preserved during regeneration"""
        store = MemorySessionStore(ttl_seconds=3600)
        
        # Create session and store tokens
        old_session_id, old_session_data = store.create_session()
        tokens = {
            'access_token': 'test_access_token',
            'refresh_token': 'test_refresh_token',
            'expires_at': (datetime.now(timezone.utc) + timedelta(hours=1)).isoformat()
        }
        store.store_tokens(old_session_id, tokens)
        
        # Regenerate session
        new_session_id, new_session_data = store.regenerate_session(old_session_id)
        
        # Retrieve tokens from new session
        retrieved_tokens = store.retrieve_tokens(new_session_id)
        
        assert retrieved_tokens is not None
        assert retrieved_tokens['access_token'] == 'test_access_token'
        assert retrieved_tokens['refresh_token'] == 'test_refresh_token'
        
        # Old session should not have tokens anymore
        old_tokens = store.retrieve_tokens(old_session_id)
        assert old_tokens is None
    
    def test_session_regeneration_thread_safety(self):
        """Test that session regeneration is thread-safe"""
        import threading
        
        store = MemorySessionStore(ttl_seconds=3600)
        old_session_id, old_session_data = store.create_session()
        old_session_data['counter'] = 0
        
        results = []
        
        def regenerate_session():
            new_id, new_data = store.regenerate_session(old_session_id)
            results.append((new_id, new_data))
        
        # Try to regenerate from multiple threads
        threads = [threading.Thread(target=regenerate_session) for _ in range(5)]
        for t in threads:
            t.start()
        for t in threads:
            t.join()
        
        # Only one should succeed, others should get None
        successful = [r for r in results if r[0] is not None]
        failed = [r for r in results if r[0] is None]
        
        assert len(successful) == 1
        assert len(failed) == 4
    
    def test_session_regeneration_uniqueness(self):
        """Test that regenerated session IDs are unique"""
        store = MemorySessionStore(ttl_seconds=3600)
        
        # Create multiple sessions and regenerate them
        regenerated_ids = []
        for _ in range(10):
            old_id, _ = store.create_session()
            new_id, _ = store.regenerate_session(old_id)
            regenerated_ids.append(new_id)
        
        # All regenerated IDs should be unique
        assert len(regenerated_ids) == len(set(regenerated_ids))
    
    def test_attack_scenario_session_fixation_prevented(self):
        """
        Test that session fixation attack is prevented.
        
        Attack Scenario:
        1. Attacker visits site and gets session ID 'ATTACKER_SESSION'
        2. Attacker tricks victim into using session ID 'ATTACKER_SESSION'
        3. Victim logs in with session ID 'ATTACKER_SESSION'
        4. Session ID is regenerated to 'NEW_SESSION'
        5. Attacker tries to use 'ATTACKER_SESSION' - should fail
        6. Only victim with 'NEW_SESSION' has access
        """
        store = MemorySessionStore(ttl_seconds=3600)
        
        # Step 1: Attacker gets a session
        attacker_session_id, attacker_session_data = store.create_session()
        assert attacker_session_data['authenticated'] is False
        
        # Step 2-3: Victim uses the same session (attacker tricked them)
        # and then authenticates
        victim_session_data = store.get(attacker_session_id)
        assert victim_session_data is not None
        
        # Step 3: Victim authenticates - session should be regenerated
        victim_session_data['authenticated'] = True
        victim_session_data['user'] = {'sub': 'victim123', 'email': 'victim@example.com'}
        
        new_session_id, new_session_data = store.regenerate_session(attacker_session_id)
        
        # Step 4: Verify new session is created
        assert new_session_id != attacker_session_id
        assert new_session_data['authenticated'] is True
        assert new_session_data['user']['sub'] == 'victim123'
        
        # Step 5: Attacker tries to use old session ID - should fail
        attacker_access = store.get(attacker_session_id)
        assert attacker_access is None  # Old session is invalidated
        
        # Step 6: Only victim with new session ID has access
        victim_access = store.get(new_session_id)
        assert victim_access is not None
        assert victim_access['authenticated'] is True
        assert victim_access['user']['sub'] == 'victim123'


class TestSessionFixationIntegration:
    """Integration tests for session fixation protection in OAuth flow"""
    
    def create_jwt(self, payload):
        """Helper to create a JWT token for testing"""
        header = {'alg': 'RS256', 'typ': 'JWT'}
        header_b64 = base64.urlsafe_b64encode(
            json.dumps(header).encode('utf-8')
        ).rstrip(b'=').decode('ascii')
        payload_b64 = base64.urlsafe_b64encode(
            json.dumps(payload).encode('utf-8')
        ).rstrip(b'=').decode('ascii')
        return f'{header_b64}.{payload_b64}.fake_signature'
    
    @patch('oauth.extract_user')
    @patch('oauth.exchange_code_for_token')
    def test_oauth_callback_regenerates_session(self, mock_exchange, mock_extract_user):
        """Test that OAuth callback regenerates session ID after authentication"""
        from flask import Flask, g, request
        from oauth import register_oauth_routes, build_oauth_config
        
        app = Flask(__name__)
        app.config['TESTING'] = True
        app.secret_key = 'test_secret_key'
        
        # Mock OAuth config
        oauth_config = {
            'enabled': True,
            'client_id': 'test_client',
            'client_secret': 'test_secret',
            'authorization_endpoint': 'https://auth.example.com/authorize',
            'token_endpoint': 'https://auth.example.com/token',
            'redirect_uri': 'https://app.example.com/callback',
            'scope': 'openid profile email',
            'session_cookie_name': 'test_session',
            'cookie_secure': False,
            'cookie_samesite': 'Lax',
            'session_ttl': 3600,
            'required_groups': [],
            'state_secret': 'test_state_secret',
            'state_max_age': 600,
            'wellknown_uri': 'https://auth.example.com/.well-known/openid-configuration'
        }
        
        store = MemorySessionStore(ttl_seconds=3600)
        
        # Add session middleware to set g.session_id and g.session_data
        @app.before_request
        def _load_session():
            session_id = request.cookies.get(oauth_config['session_cookie_name'])
            session_data = store.get(session_id)
            if not session_data:
                session_id, session_data = store.create_session()
                g.session_is_new = True
            g.session_id = session_id
            g.session_data = session_data
        
        @app.after_request
        def _persist_session(response):
            session_id = getattr(g, 'session_id', None)
            if session_id:
                response.set_cookie(
                    oauth_config['session_cookie_name'],
                    session_id,
                    httponly=True,
                    secure=oauth_config['cookie_secure'],
                    samesite=oauth_config['cookie_samesite'],
                    max_age=oauth_config['session_ttl'],
                    path='/'
                )
            return response
        
        # Create a mock limiter
        mock_limiter = Mock()
        mock_limiter.limit = lambda *args, **kwargs: lambda f: f  # No-op decorator
        
        register_oauth_routes(app, oauth_config, store, mock_limiter)
        
        # Mock token exchange response
        payload = {
            'sub': 'user123',
            'email': 'test@example.com',
            'name': 'Test User',
            'exp': int((datetime.now(timezone.utc) + timedelta(hours=1)).timestamp())
        }
        id_token = self.create_jwt(payload)
        
        mock_exchange.return_value = {
            'access_token': 'test_access_token',
            'id_token': id_token,
            'expires_in': 3600
        }
        
        # Mock extract_user to return user data
        mock_extract_user.return_value = {
            'sub': 'user123',
            'email': 'test@example.com',
            'name': 'Test User',
            'groups': []
        }
        
        with app.test_client() as client:
            # Simulate OAuth flow
            # 1. Initiate login to get a session
            with client.session_transaction() as sess:
                # Pre-create a session with PKCE data
                pass
            
            response = client.get('/oauth/login')
            assert response.status_code == 302  # Redirect to auth provider
            
            # Get the session cookie from response
            old_session_id = None
            if 'Set-Cookie' in response.headers:
                for header_value in response.headers.getlist('Set-Cookie'):
                    if 'test_session=' in header_value:
                        # Extract session ID from Set-Cookie header
                        cookie_parts = header_value.split(';')[0]
                        old_session_id = cookie_parts.split('=')[1]
                        break
            
            assert old_session_id is not None
            
            # Verify session exists and is unauthenticated
            old_session = store.get(old_session_id)
            assert old_session is not None
            assert old_session.get('authenticated') is False
            
            # 2. Simulate OAuth callback with authorization code
            # Get the state that was generated during login
            pkce_data = old_session.get('pkce', {})
            assert 'state' in pkce_data, "PKCE state should be set after login"
            state_param = pkce_data['state']
            
            # Make callback request with the actual state from the session
            response = client.get(f'/oauth/callback?code=test_code&state={state_param}')
            assert response.status_code == 302  # Redirect to home
            
            # Get the new session cookie from response
            new_session_id = None
            if 'Set-Cookie' in response.headers:
                for header_value in response.headers.getlist('Set-Cookie'):
                    if 'test_session=' in header_value:
                        # Extract session ID from Set-Cookie header
                        cookie_parts = header_value.split(';')[0]
                        new_session_id = cookie_parts.split('=')[1]
                        break
            
            # CRITICAL TEST: Session ID should have changed
            assert new_session_id != old_session_id
            
            # Old session should be invalidated
            old_session_check = store.get(old_session_id)
            assert old_session_check is None
            
            # New session should be authenticated
            new_session = store.get(new_session_id)
            assert new_session is not None
            assert new_session.get('authenticated') is True
            assert new_session.get('user') is not None
            assert new_session['user']['sub'] == 'user123'


if __name__ == '__main__':
    pytest.main([__file__, '-v'])
